const BASE = window.NOTA_DATA;
const STORE_KEY = "nota-v1";
const state = { route:"today", month:new Date(2026,7,1), selectedDate:"2026-08-31", library:"reading", search:"", filter:"all", data:load() };
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORE_KEY));return saved?{...clone(BASE),...saved}:clone(BASE)}catch{return clone(BASE)}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state.data))}
function esc(s=""){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function topic(id){return state.data.topics[id]||{name:id,color:"#777",soft:"#eee"}}
function chips(ids=[]){return ids.map(id=>{const t=topic(id);return `<span class="chip" style="--topic:${t.color};--soft:${t.soft}">${esc(t.name)}</span>`}).join("")}
function entryCard(e){const t=topic(e.topics?.[0]);return `<article class="entry" data-entry="${e.id}" style="--topic:${t.color}"><div class="entry-meta"><span class="type-label">${esc(e.type)}</span>${chips(e.topics)}</div><h3>${e.type==="Quote"?`“${esc(e.title)}”`:esc(e.title)}</h3>${e.author?`<p>${esc(e.author)}</p>`:e.excerpt?`<p>${esc(e.excerpt)}</p>`:""}</article>`}
function pageHead(kicker,title,lede=""){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h1 class="page-title">${title}</h1>${lede?`<p class="lede">${lede}</p>`:""}</div></div>`}
function today(){const entries=state.data.entries.filter(e=>e.occurredAt==="2026-08-31"), memory=state.data.entries.find(e=>e.occurredAt==="2025-08-31"), quote=state.data.entries.find(e=>e.type==="Quote");return `<section><div class="page-head"><div><p class="eyebrow">A record of a life</p><h1 class="page-title">Today</h1></div><div class="date-large">Monday<b>31 August 2026</b></div></div><div class="memory">On this day last year — <a href="#" data-entry="${memory.id}">${esc(memory.title)}</a></div><div class="today-grid"><div><h2 class="section-title">Entries</h2><div class="entry-list">${entries.map(entryCard).join("")}</div></div><aside><h2 class="section-title">To-do</h2><div class="tasks">${state.data.tasks.map(taskRow).join("")}</div><div class="quote-card"><p class="eyebrow">A thought to keep</p><blockquote>“${esc(quote.title)}”</blockquote><cite>${esc(quote.author)}</cite></div></aside></div></section>`}
function taskRow(t){const tp=topic(t.topics[0]);return `<label class="task ${t.completedAt?"done":""}"><input type="checkbox" data-task="${t.id}" ${t.completedAt?"checked":""}><span class="task-title">${esc(t.title)}</span><span class="chip" style="--topic:${tp.color};--soft:${tp.soft}">${esc(tp.name)}</span></label>`}
function monthEntries(date){return state.data.entries.filter(e=>e.occurredAt===date)}
function calendar(){const y=state.month.getFullYear(),m=state.month.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),cells=[];for(let i=0;i<start;i++)cells.push(`<button class="day muted" disabled></button>`);for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,es=monthEntries(date),dots=[...new Set(es.flatMap(e=>e.topics))].slice(0,3).map(id=>`<i class="dot" style="background:${topic(id).color}"></i>`).join("");cells.push(`<button class="day ${date===state.selectedDate?"selected":""}" data-date="${date}"><span>${d}</span><span class="dots">${dots}</span></button>`)}const selected=monthEntries(state.selectedDate),label=new Date(state.selectedDate+"T12:00:00").toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"});return `<section>${pageHead("Browse the archive","Calendar","Every item keeps its own dates; the calendar simply gathers the record of each day.")}<div class="calendar-shell"><div><div class="calendar-head"><button class="icon-button" data-month="-1" aria-label="Previous month">←</button><h2>${first.toLocaleDateString("en-GB",{month:"long",year:"numeric"})}</h2><button class="icon-button" data-month="1" aria-label="Next month">→</button></div><div class="week">${["M","T","W","T","F","S","S"].map(x=>`<span>${x}</span>`).join("")}</div><div class="calendar-grid">${cells.join("")}</div></div><aside class="selected-day"><p class="eyebrow">Selected day</p><h3>${label}</h3>${selected.length?selected.map(entryCard).join(""):`<p class="empty">Nothing recorded on this day.</p>`}</aside></div></section>`}
function library(){let body="";if(state.library==="reading")body=`<div class="book-grid">${state.data.books.map((b,i)=>`<article class="book"><span class="book-number">0${i+1}</span><h3>${esc(b.title)}</h3><p>${esc(b.author)}</p><span class="status">${esc(b.status.replaceAll("-"," "))}${b.status==="reading"?` · ${b.progress}%`:""}</span><div class="progress"><i style="width:${b.progress}%"></i></div></article>`).join("")}</div>`;else if(state.library==="quotes")body=`<div class="quote-list">${state.data.entries.filter(e=>e.type==="Quote").map(e=>`<blockquote class="library-quote" data-entry="${e.id}">“${esc(e.title)}”<cite>${esc(e.author)}</cite></blockquote>`).join("")}</div>`;else body=`<div class="entry-list">${state.data.entries.filter(e=>["Note","Journal","Journey"].includes(e.type)).map(entryCard).join("")}</div>`;return `<section>${pageHead("Things worth keeping","Library","Books, quotations and notes live together, linked by topic but never confused with their type.")}<div class="library-tabs">${["reading","quotes","notes"].map(x=>`<button class="filter ${state.library===x?"active":""}" data-library="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join("")}</div>${body}</section>`}
function topics(){return `<section>${pageHead("Paths through the archive","Topics","Topics cut across journals, books, quotes and journeys. One item can belong to several.")}<div class="topic-grid">${Object.entries(state.data.topics).map(([id,t])=>{const count=state.data.entries.filter(e=>e.topics?.includes(id)).length;return `<button class="topic-card" data-topic="${id}" style="--topic:${t.color};--soft:${t.soft}"><span class="topic-count">${count} ${count===1?"item":"items"}</span><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p></button>`}).join("")}</div></section>`}
function search(){const q=state.search.toLowerCase(),types=["all","Journal","Note","Reading","Quote","Journey","Task","Event"],items=[...state.data.entries,...state.data.tasks.map(t=>({...t,type:"Task",excerpt:""}))].filter(e=>(state.filter==="all"||e.type===state.filter)&&(!q||[e.title,e.excerpt,e.author,...(e.topics||[]).map(x=>topic(x).name)].join(" ").toLowerCase().includes(q)));return `<section>${pageHead("Find anything","Search","Search across titles, words, types and topics.")}<input class="search-box" type="search" value="${esc(state.search)}" placeholder="Search nota…" autofocus><div class="search-filters">${types.map(t=>`<button class="filter ${state.filter===t?"active":""}" data-filter="${t}">${t}</button>`).join("")}</div><div class="entry-list search-results">${items.length?items.map(entryCard).join(""):`<p class="empty">No matching records.</p>`}</div></section>`}
function topicView(id){const t=topic(id),items=state.data.entries.filter(e=>e.topics?.includes(id));return `<section><div class="page-head"><div><p class="eyebrow">Topic</p><h1 class="page-title" style="color:${t.color}">${esc(t.name)}</h1><p class="lede">${esc(t.description)}</p></div></div><div class="entry-list">${items.map(entryCard).join("")}</div></section>`}
function render(){const hash=location.hash.slice(1)||"today",[route,arg]=hash.split("/");state.route=route;document.querySelectorAll(".main-nav a,.mobile-nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")===`#${route}`));document.getElementById("app").innerHTML=route==="calendar"?calendar():route==="library"?library():route==="topics"?(arg?topicView(arg):topics()):route==="search"?search():today();document.getElementById("app").focus({preventScroll:true})}
function modal(inner){document.getElementById("modal-root").innerHTML=`<div class="modal-backdrop" data-close><div class="modal" role="dialog" aria-modal="true">${inner}</div></div>`}
function closeModal(){document.getElementById("modal-root").innerHTML=""}
function capture(){const types=["Journal","Note","Task","Event","Reading","Quote","Journey","Collection"];modal(`<div class="modal-head"><h2>Add to nota</h2><button class="close" data-close aria-label="Close">×</button></div><form id="capture-form"><div class="type-picker">${types.map((t,i)=>`<button type="button" class="${i===0?"active":""}" data-pick="${t}">${t}</button>`).join("")}</div><input type="hidden" name="type" value="Journal"><div class="field"><label>What would you like to keep?</label><input name="title" required placeholder="A title or thought"></div><div class="field"><label>More detail</label><textarea name="body" placeholder="Write as much or as little as you like"></textarea></div><div class="field"><label>Topic</label><select name="topic">${Object.entries(state.data.topics).map(([id,t])=>`<option value="${id}">${t.name}</option>`).join("")}</select></div><div class="field"><label>Date</label><input name="date" type="date" value="2026-08-31"></div><button class="submit">Keep this</button></form>`)}
function detail(id){const e=[...state.data.entries,...state.data.tasks].find(x=>x.id===id);if(!e)return;modal(`<article class="entry-detail"><div class="modal-head"><span class="type-label">${esc(e.type||"Task")}</span><button class="close" data-close>×</button></div>${chips(e.topics)}<h2 class="detail-title">${e.type==="Quote"?`“${esc(e.title)}”`:esc(e.title)}</h2><p class="detail-body">${esc(e.excerpt||e.author||"Saved in your Nota archive.")}</p><p class="eyebrow">${esc(e.occurredAt||e.dueAt||"")}</p></article>`)}
function toast(msg){const el=document.getElementById("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
document.addEventListener("click",e=>{const a=e.target.closest("[data-action='capture']");if(a)capture();const close=e.target.closest("[data-close]");if(close&&e.target===close)closeModal();const pick=e.target.closest("[data-pick]");if(pick){document.querySelectorAll("[data-pick]").forEach(x=>x.classList.remove("active"));pick.classList.add("active");document.querySelector("[name=type]").value=pick.dataset.pick}const entry=e.target.closest("[data-entry]");if(entry){e.preventDefault();detail(entry.dataset.entry)}const task=e.target.closest("[data-task]");if(task){const t=state.data.tasks.find(x=>x.id===task.dataset.task);t.completedAt=task.checked?"2026-08-31":null;save();render();toast(task.checked?"Task completed":"Task reopened")}const date=e.target.closest("[data-date]");if(date){state.selectedDate=date.dataset.date;render()}const month=e.target.closest("[data-month]");if(month){state.month=new Date(state.month.getFullYear(),state.month.getMonth()+Number(month.dataset.month),1);render()}const lib=e.target.closest("[data-library]");if(lib){state.library=lib.dataset.library;render()}const filter=e.target.closest("[data-filter]");if(filter){state.filter=filter.dataset.filter;render()}const tp=e.target.closest("[data-topic]");if(tp)location.hash=`topics/${tp.dataset.topic}`;if(e.target.closest(".menu-button")){const nav=document.querySelector(".main-nav");nav.classList.toggle("open");document.querySelector(".menu-button").setAttribute("aria-expanded",nav.classList.contains("open"))}if(e.target.closest(".main-nav a"))document.querySelector(".main-nav").classList.remove("open")});
document.addEventListener("input",e=>{if(e.target.matches(".search-box")){state.search=e.target.value;const pos=e.target.selectionStart;document.querySelector(".search-results").innerHTML=(()=>{const q=state.search.toLowerCase(),items=[...state.data.entries,...state.data.tasks.map(t=>({...t,type:"Task"}))].filter(x=>(state.filter==="all"||x.type===state.filter)&&[x.title,x.excerpt,x.author,...(x.topics||[]).map(y=>topic(y).name)].join(" ").toLowerCase().includes(q));return items.length?items.map(entryCard).join(""):`<p class="empty">No matching records.</p>`})();e.target.setSelectionRange(pos,pos)}});
document.addEventListener("submit",e=>{if(e.target.id!=="capture-form")return;e.preventDefault();const f=new FormData(e.target),type=f.get("type"),id=`u${Date.now()}`,item={id,type,title:f.get("title"),excerpt:f.get("body"),topics:[f.get("topic")],occurredAt:f.get("date"),createdAt:f.get("date"),publishedAt:f.get("date")};if(type==="Task")state.data.tasks.unshift({id,title:item.title,topics:item.topics,dueAt:item.occurredAt,completedAt:null});else state.data.entries.unshift(item);save();closeModal();render();toast("Saved to nota")});
window.addEventListener("hashchange",render);render();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
